'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Table
    Public Property OgrId As Integer
    Public Property OgrAd As String
    Public Property OgrSoyad As String
    Public Property OgrMail As String
    Public Property OgrFotograf As String
    Public Property OgrAdres As String

End Class
